# Generated by Django 3.2.8 on 2021-10-29 13:34

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0002_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('barcode', core.fields.BarcodeField(unique=True)),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  to='references.subdivision',
                                                  verbose_name='Подразделение')),
                ('person', models.ForeignKey(blank=True, null=True,
                                             on_delete=django.db.models.deletion.SET_NULL,
                                             to='references.person', verbose_name='Получатель')),
                ('address', models.ForeignKey(blank=True, null=True,
                                              on_delete=django.db.models.deletion.SET_NULL,
                                              to='references.address',
                                              verbose_name='Адрес доставки')),
                ('phone', models.ForeignKey(blank=True, null=True,
                                            on_delete=django.db.models.deletion.SET_NULL,
                                            to='references.phone',
                                            verbose_name='Телефон получателя')),
                ('notice_number', models.PositiveIntegerField(blank=True, null=True,
                                                              verbose_name='№ извещения')),
                ('dt_cr', core.fields.CreateDateTimeField()),
                ('dt_up', core.fields.UpdateDateTimeField()),
            ],
            options={
                'verbose_name': 'отправление',
                'verbose_name_plural': 'отправления',
                'db_table': 'mdl_dlv_mailing',
            },
        ),
    ]
