# Generated by Django 3.2.8 on 2021-11-05 12:56

import apps.account.models
import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('sessions', '0001_initial'),
        ('references', '0003_related'),
        ('apps_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', apps.account.models.PersonManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='users', to='references.employee',
                                    verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='users', to='references.subdivision',
                                    verbose_name='Подразделение'),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='sessions', to=settings.AUTH_USER_MODEL,
                                           verbose_name='Пользователь')),
                ('subdivision', models.ForeignKey(blank=True, null=True,
                                                  on_delete=django.db.models.deletion.SET_NULL,
                                                  related_name='+', to='references.subdivision',
                                                  verbose_name='Подразделение')),
                ('ipaddress', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                 to='sessions.session', verbose_name='Сессия')),
                ('dt_start', core.fields.CreateDateTimeField()),
            ],
            options={
                'verbose_name': 'сеанс пользователя',
                'verbose_name_plural': 'сеансы пользователей',
                'db_table': 'auth_user_session',
            },
        ),
    ]
