# Generated by Django 3.2.8 on 2021-10-21 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_employee'),
        ('apps_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.employee', verbose_name='сотрудник'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.subdivision', verbose_name='подразделение'),
        ),
    ]
