# Generated by Django 3.2.8 on 2021-10-21 11:24

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('type_code', core.fields.CodeField(blank=True, null=True)),
                ('type_name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('type_name_full', models.CharField(blank=True, max_length=255, null=True,
                                                    verbose_name='Наименование полное')),
                ('type_desc', models.CharField(blank=True, max_length=255, null=True,
                                               verbose_name='Описание')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   to='contenttypes.contenttype',
                                                   verbose_name='Объект')),
                ('status', core.fields.StatusField()),
            ],
            options={
                'verbose_name': 'тип',
                'verbose_name_plural': 'типы',
                'db_table': 'ref_type',
                'ordering': ['id'],
            },
        ),
    ]
