# Generated by Django 3.2.8 on 2021-10-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locationstreets',
            unique_together={('location', 'street')},
        ),
        migrations.AlterUniqueTogether(
            name='personaddresses',
            unique_together={('person', 'address')},
        ),
        migrations.AlterUniqueTogether(
            name='personphones',
            unique_together={('person', 'phone')},
        ),
        migrations.AlterUniqueTogether(
            name='postphones',
            unique_together={('post_office', 'phone')},
        ),
    ]
