# Generated by Django 3.2.8 on 2021-10-22 12:57

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='model_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_object': 3}, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='references.flextype', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', core.fields.CodeField(unique=True)),
                ('name_str', models.CharField(max_length=100, verbose_name='Наименование')),
                ('name_str_full', models.CharField(db_index=True, editable=False, max_length=150,
                                                   verbose_name='Наименование полное')),
                ('model_type', models.ForeignKey(blank=True, limit_choices_to=2, null=True,
                                                 on_delete=django.db.models.deletion.SET_NULL,
                                                 to='references.flextype', verbose_name='Тип')),
                ('dt_cr', core.fields.CreateDateTimeField()),
                ('dt_up', core.fields.UpdateDateTimeField()),
                ('status', core.fields.StatusField()),
            ],
            options={
                'verbose_name': 'улица',
                'verbose_name_plural': 'улицы',
                'db_table': 'ref_street',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
