# Generated by Django 3.2.8 on 2021-10-21 12:27

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('references', '0002_subdivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('model_type', models.ForeignKey(blank=True,
                                                 limit_choices_to={'content_type': 0}, null=True,
                                                 on_delete=django.db.models.deletion.SET_NULL,
                                                 to='references.flextype')),
                ('dt_cr', core.fields.CreateDateTimeField()),
                ('dt_up', core.fields.UpdateDateTimeField()),
                ('status', core.fields.StatusField()),
            ],
            options={
                'verbose_name': 'телефон',
                'verbose_name_plural': 'телефоны',
                'db_table': 'ref_phone',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
