# Generated by Django 3.2.8 on 2021-10-21 12:29

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('references', '0003_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(db_index=True, max_length=100,
                                               verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True,
                                                verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True,
                                                 verbose_name='Отчество')),
                ('name_lfm', models.CharField(editable=False, max_length=150,
                                              verbose_name='Фамилия И.О.')),
                ('name_fml', models.CharField(editable=False, max_length=150,
                                              verbose_name='И.О. Фамилия')),
                ('pers_num', models.CharField(blank=True, db_index=True, max_length=14, null=True,
                                              verbose_name='Личный номер')),
                ('birth_date', models.DateField(blank=True, null=True,
                                                verbose_name='Дата рождения')),
                ('gender', core.fields.GenderField()),
                ('dt_cr', core.fields.CreateDateTimeField()),
                ('dt_up', core.fields.UpdateDateTimeField()),
                ('status', core.fields.StatusField()),
            ],
            options={
                'verbose_name': 'персона',
                'verbose_name_plural': 'персоны',
                'db_table': 'ref_person',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonPhones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('phone_type', core.fields.PhoneTypeField()),
                ('status', core.fields.StatusField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             to='references.person', verbose_name='Персона')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            to='references.phone', verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Телефон персоны',
                'verbose_name_plural': 'Телефоны персоны',
                'db_table': 'ref_person_phones',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='phones',
            field=models.ManyToManyField(related_name='persons', through='references.PersonPhones',
                                         to='references.Phone', verbose_name='Телефоны'),
        ),
    ]
