# Generated by Django 3.2.8 on 2021-10-21 12:34

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('references', '0004_person_phones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_num', models.PositiveIntegerField(unique=True, verbose_name='Табельный')),
                ('person', models.ForeignKey(blank=True, null=True,
                                             on_delete=django.db.models.deletion.SET_NULL,
                                             to='references.person', verbose_name='Персона')),
                ('subdivision', models.ForeignKey(blank=True, null=True,
                                                  on_delete=django.db.models.deletion.SET_NULL,
                                                  to='references.subdivision',
                                                  verbose_name='Подразделение')),
                ('dt_cr', core.fields.CreateDateTimeField()),
                ('dt_up', core.fields.UpdateDateTimeField()),
                ('status', core.fields.StatusField()),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'db_table': 'ref_employee',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
