# Generated by Django 3.2.8 on 2021-10-21 12:37

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('references', '0005_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', core.fields.CodeField(unique=True)),
                ('name_cnt', models.CharField(max_length=60, verbose_name='Наименование')),
                ('alpha2', models.CharField(max_length=2, verbose_name='Код2')),
                ('alpha3', models.CharField(max_length=3, verbose_name='Код3')),
                ('dt_cr', core.fields.CreateDateTimeField()),
                ('dt_up', core.fields.UpdateDateTimeField()),
                ('status', core.fields.StatusField()),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
                'db_table': 'ref_country',
                'abstract': False,
            },
        ),
    ]
