# Generated by Django 3.2.8 on 2021-10-21 12:37

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('references', '0006_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', core.fields.CodeField(unique=True)),
                ('name_rgn', models.CharField(max_length=60, verbose_name='Наименование')),
                ('country', models.ForeignKey(blank=True, null=True,
                                              on_delete=django.db.models.deletion.SET_NULL,
                                              to='references.country', verbose_name='Страна')),
                ('dt_cr', core.fields.CreateDateTimeField()),
                ('dt_up', core.fields.UpdateDateTimeField()),
                ('status', core.fields.StatusField()),
            ],
            options={
                'verbose_name': 'область',
                'verbose_name_plural': 'области',
                'db_table': 'ref_region',
                'abstract': False,
            },
        ),
    ]
