# Generated by Django 3.2.8 on 2021-10-21 12:38

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('references', '0008_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', core.fields.CodeField(unique=True)),
                ('soato', models.BigIntegerField(unique=True, verbose_name='СОАТО')),
                ('name_lct', models.CharField(max_length=100, verbose_name='Наименование')),
                ('name_lct_full', models.CharField(editable=False, max_length=150,
                                                   verbose_name='Наименование полное')),
                ('district', models.ForeignKey(blank=True, null=True,
                                               on_delete=django.db.models.deletion.SET_NULL,
                                               to='references.district', verbose_name='район')),
                ('model_type', models.ForeignKey(blank=True, limit_choices_to={'content_type': 0},
                                                 null=True,
                                                 on_delete=django.db.models.deletion.SET_NULL,
                                                 to='references.flextype')),
                ('dt_cr', core.fields.CreateDateTimeField()),
                ('dt_up', core.fields.UpdateDateTimeField()),
                ('status', core.fields.StatusField()),
            ],
            options={
                'verbose_name': 'населенный пункт',
                'verbose_name_plural': 'населенные пункты',
                'db_table': 'ref_location',
                'abstract': False,
            },
        ),
    ]
