# Generated by Django 3.2.8 on 2021-10-29 12:15

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('desc', models.CharField(blank=True, max_length=255, null=True,
                                          verbose_name='Описание')),
                ('route', models.CharField(blank=True, max_length=100, null=True,
                                           verbose_name='Имя маршрута')),
                ('perm', models.CharField(blank=True, max_length=100, null=True,
                                          verbose_name='Разрешение')),
                ('icon', models.CharField(blank=True, default='fas fa-microchip', max_length=30,
                                          null=True, verbose_name='Иконка')),
                ('sort', models.SmallIntegerField(db_index=True, default=999,
                                                  verbose_name='Сортировка')),
                ('status', core.fields.StatusField()),
            ],
            options={
                'verbose_name': 'модуль',
                'verbose_name_plural': 'модули',
                'db_table': 'mdl_module',
            },
        ),
    ]
